### PR TITLE
[6.0] Fix semantics of AvlTree.insert & new AvlTree.insertOrUpdate method 

### LINKED ISSUE #908: [v6.0] Fix semantics of AvlTree.insert
Current (v5.0) semantics is not consistent with AvlTree.update.
https://github.com/ScorexFoundation/sigmastate-interpreter/blob/3da19f01798bfa17620dcb5ad8ed327f9217f755/interpreter/shared/src/main/scala/sigmastate/types.scala#L2328

### PR DESCRIPTION
**Pull request by kushti**
close #908 

In this PR, semantics of AvlTree.insert fixed, and new AvlTree.insertOrUpdate method added

### CODE REVIEW

File: data/shared/src/main/scala/sigma/eval/AvlTreeVerifier.scala [hunk 1]
```diff
@@ -50,6 +50,18 @@ trait AvlTreeVerifier {
...
 
+  /**
+    * Returns Failure if the proof does not verify.
+    * Otherwise, successfully modifies tree and so returns Success.
+    * After one failure, all subsequent operations with this verifier will fail and digest
+    * is None.
+    *
+    * @param key   key to look up
+    * @param value value to check it was inserted or updated
+    * @return Success(Some(value)), Success(None), or Failure
```
Comment (aslesarenko) [inline data/shared/src/main/scala/sigma/eval/AvlTreeVerifier.scala:61]: Make sense to describe each case of returned result.

File: interpreter/shared/src/main/scala/sigmastate/eval/Extensions.scala [hunk 2]
```diff
@@ -120,6 +120,24 @@ object Extensions {
       }
     }
 
+    def insertOrUpdate(
+                entries: Coll[(Coll[Byte], Coll[Byte])],
+                proof: Coll[Byte]): Option[AvlTree] = {
+      if (!tree.isInsertAllowed || !tree.isUpdateAllowed) {
```
Comment (aslesarenko) [inline interpreter/shared/src/main/scala/sigmastate/eval/Extensions.scala:126]: Both flags are required, however for each given tree it will either be insert or update (but not both).
Is it possible to make it more flexible and require the flag only if the corresponding operation is happening for a given tree.

File: interpreter/shared/src/main/scala/sigmastate/interpreter/CErgoTreeEvaluator.scala [hunk 3]
```diff
@@ -146,7 +146,7 @@ class CErgoTreeEvaluator(
           val insertRes = bv.performInsert(key.toArray, value.toArray)
           // TODO v6.0: throwing exception is not consistent with update semantics
           //  however it preserves v4.0 semantics (see https://github.com/ScorexFoundation/sigmastate-interpreter/issues/908)
```
Comment (aslesarenko) [inline interpreter/shared/src/main/scala/sigmastate/interpreter/CErgoTreeEvaluator.scala:148]: todo can be removed.

File: interpreter/shared/src/main/scala/sigmastate/interpreter/CErgoTreeEvaluator.scala [hunk 4]
```diff
@@ -192,6 +192,37 @@ class CErgoTreeEvaluator(
...
+    } else {
+      val bv     = createVerifier(tree, proof)
+      // when the tree is empty we still need to add the insert cost
+      val nItems = Math.max(bv.treeHeight, 1)
+
+      // here we use forall as looping with fast break on first failed tree operation
+      operations.forall { case (key, value) =>
+        var res = true
+        // the cost of tree update is O(bv.treeHeight)
+        addSeqCost(UpdateAvlTree_Info, nItems) { () =>
```
Comment (aslesarenko) [inline interpreter/shared/src/main/scala/sigmastate/interpreter/CErgoTreeEvaluator.scala:211]:
```suggestion
      // Here (and in the previous methods) the cost is not properly approximated. 
      // When the tree is small (or empty), but there are many `operations`, the treeHeight will grow on every iteration. 
      // So should the cost on every iteration.
      addSeqCost(UpdateAvlTree_Info, nItems) { () =>
```

**Review by aslesarenko — APPROVED** [review]
LGTM, but see comments.

File: interpreter/shared/src/main/scala/sigmastate/eval/Extensions.scala (hunk 2 above)
Comment (kushti) [reply interpreter/shared/src/main/scala/sigmastate/eval/Extensions.scala:126]: " for each given tree it will either be insert or update (but not both)" - no, it could be insert for one key and update for another

File: interpreter/shared/src/main/scala/sigmastate/interpreter/CErgoTreeEvaluator.scala (hunk 3 above)
Comment (kushti) [reply interpreter/shared/src/main/scala/sigmastate/interpreter/CErgoTreeEvaluator.scala:148]: done

File: data/shared/src/main/scala/sigma/eval/AvlTreeVerifier.scala (hunk 1 above)
Comment (kushti) [reply data/shared/src/main/scala/sigma/eval/AvlTreeVerifier.scala:61]: done
